# Umask
umask 022

# Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# End of Zinit's installer chunk
 
# --- ZSH PLUGINS PARAMS ---
# zsh-nvm
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

# python
export PYTHON_AUTO_VRUN=true
export PYTHON_VENV_NAME='.venv'

# --- ZSH PLUGINS ---
# NVM - must be first because launch node.js
zinit ice wait lucid; zinit light lukechilds/zsh-nvm

# Oh My Zsh plugins
zinit ice wait lucid; zinit snippet OMZP::git
zinit ice wait lucid; zinit snippet OMZP::python

# Completions and suggestions
zinit ice wait lucid atinit'ZINIT[COMPINIT_OPTS]=-C; zicompinit'
zinit light zsh-users/zsh-completions
zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# Other
zinit ice wait lucid; zinit light Aloxaf/fzf-tab

# Highlighting - must be last
zinit ice wait lucid
zinit light zdharma-continuum/fast-syntax-highlighting

# User configuration
source "$HOME/.zsh_custom"

