# Umask
umask 022

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Starship config file
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# Python venv zsh plugin
export PYTHON_AUTO_VRUN=true
export PYTHON_VENV_NAME=".venv"

# Add John the Ripper to PATH
export PATH="$PATH:/opt/john-the-ripper"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME='fox'

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    sudo
    python
    jsontools
    dirhistory
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.

# Oh My Zsh some lib/directories.zsh unaliases
unalias -- -
unalias 1
unalias 2
unalias 3
unalias 4
unalias 5
unalias 6
unalias 7
unalias 8
unalias 9

unalias md
unalias rd

unalias l
unalias ll
unalias la
unalias lsa

# --- CLI UTILS ---
# Aliases for eza
unset LS_COLORS
alias ls='eza -lbF --group-directories-first --no-time --smart-group --icons --git'
alias la='eza -lbaF --group-directories-first --no-time --smart-group --icons --git'
alias lss='eza -lbF --group-directories-first --no-time --smart-group --icons --git --total-size'
alias las='eza -lbaF --group-directories-first --no-time --smart-group --icons --git --total-size'

# Atuin init
eval "$(atuin init zsh)"

# fzf init
source <(fzf --zsh)

# Starship init
eval "$(starship init zsh)"

# Shellfirm init
eval "$(shellfirm init zsh)"

# Zoxide init
eval "$(zoxide init zsh --cmd cd)"

# --- PENTEST TOOLS ---
# Aliases for John the Ripper
alias john='/opt/john-the-ripper/john'

# Aliases for dirsearch
alias dirsearch='/opt/dirsearch/.venv/bin/python /opt/dirsearch/dirsearch.py'
