# Change prefix bind to Alt + a
set -g prefix 'M-a'
unbind 'C-b'
bind 'M-a' send-prefix

# Start windows and panel numeration at 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Select mode vi binds
setw -g mode-keys vi

# Reload config at Prefix + r
bind 'r' source-file ~/.tmux.conf \; display-message "Reloaded!"

# Change windows split binds
bind '|' split-window -h
bind '\' split-window -v
unbind '"'
unbind '%'

